version: "3.9"
services:
  movie:
    build: ./movie/
    ports:
      - "3200:3200"
  showtime:
    build: ./showtime/
    ports:
      - "3202:3202"
  user:
    build: ./user/
    ports:
      - "3203:3203"
    depends_on:
      - booking
      - movie
  booking:
    build: ./booking/
    ports:
      - "3201:3201"
    depends_on:
      - showtime
